### ISSUE TITLE
Compatible issues

### ISSUE THREAD

**Issue by superpupervlad** [NakedSnake26/Nier-Automata-Theme#3]
Hello, your theme looks pretty cool but I can't install it because it's not compatible with latest IDE version.
It would be great if you update theme.

**Comment by NakedSnake26** [comment]
Hello. Thanks for the feedback.
I checked current version of plugin and it really doesn't work on "IDEA 2022.1" or just above 2022.
This will be fixed soon.

**Comment by NakedSnake26** [comment]
Hello @superpupervlad. Plugin has been updated to the new version 2022. Thanks for feedback.
